//  function myFunction() {
//   var x = document.getElementById("myTopnav");
//   if (x.className === "topnav") {
//     x.className += " responsive";
//   } else {
//     x.className = "topnav";
//   }
// }

//declare name of character searched from HTML input
var searchName = $("#character-search").val().trim();

function charBio () {
  var searchName = $("#character-search").val().trim();
  var settings = {
    "async": true,
    "crossDomain": true,
    "url": "https://superhero-search.p.rapidapi.com/?hero=" + searchName,
    "method": "GET",
    "headers": {
      "x-rapidapi-host": "superhero-search.p.rapidapi.com",
      "x-rapidapi-key": "5470b880aamsh37bac69440bf26dp130d2djsn9d4d83f96816"
    }
  }
  
  $.ajax(settings).then(function (response) {
    console.log(response);
    const charCard = $("<div>").attr("class","card");
    $("#bio").append(charCard);
    
    

  });
  }
  
//
function characterSearch() {
  const hash = "f3ca3e169c9bd8ca02d93185989ba9cc";
  const apiKey = "6ac5ff42f16a138a51581025d4b3838f";
  const searchName = $("#character-search").val().trim();
  //queryUrl built with md5
  const queryUrl =
    "http://gateway.marvel.com/v1/public/characters?name=" +
    searchName +
    "&ts=1&apikey=6ac5ff42f16a138a51581025d4b3838f&hash=f3ca3e169c9bd8ca02d93185989ba9cc";

  $.ajax({
    url: queryUrl,
    method: "GET",
  }).then(function (response) {
    // console.log(response);
    comicSearch(response.data.results[0].id);
  });
  // charBio();
}

var coverIndex = [];
//function to use character ID generated by user search to populate comic covers to Comics HTML page
function comicSearch(charID) {
  const hash = "f3ca3e169c9bd8ca02d93185989ba9cc";
  const apiKey = "6ac5ff42f16a138a51581025d4b3838f";
  const queryUrl2 =
    "http://gateway.marvel.com/v1/public/characters/" +
    charID +
    "/comics?&ts=1&apikey=6ac5ff42f16a138a51581025d4b3838f&hash=f3ca3e169c9bd8ca02d93185989ba9cc";

  $.ajax({
    url: queryUrl2,
    method: "GET",
  }).then(function (response) {
    // console.log(response);
    // let i = 0;
    // console.log(response.data.results[i].images[i]);

    const coverIndex = response.data.results;
    let count = 0;
    let newRow = $("<div>").attr("class", "columns");
    //create for loop here to loop through 18
    for (let i = 0; i < coverIndex.length; i++) {
      if (count === 4) {
        $("#comics").append(newRow);
        count = 0;
        newRow = $("<div>").attr("class", "columns");
      }
      // console.log(response.data.results[i])
      // console.log(response.data.results[i].images)

      const newCol = $("<div>").attr("class", "column");
      newRow.append(newCol);
      // const apiImageArray = response.data.results[i].images[i];
      const coverThumbUrl = response.data.results[i].thumbnail.path;
      //   if (apiImageArray !== 0) {
      //   i++;
      // }
      const coverImage = coverThumbUrl + ".jpg";
      newCol.append(
        $("<img>")
          .attr("src", coverImage)
          .attr("alt", "comic cover")
          .css("width:", "100%")
      );
      count++;
    }
  });
}


$("#searchBtnComics").on("click", function (event) {
  event.preventDefault();
  const searchName = $("#character-search").val().trim();
  charBio();
  characterSearch();
  // console.log(searchName);
});
